[pytest]
testpaths = tests
markers =
    slow: test long (import de tous les modules en interpréteurs séparés)
filterwarnings =
    ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning
